### PR TITLE
SpeedDial: Add searchbar

### PR DESCRIPTION
**Pull request by Diablopc**
- Disabled

- Enabled

- In config

### CODE REVIEW

**Comment by Martii** [comment]
@Diablopc 
Best to make a branch on your repository, and ensure that your master is up to date before that so comments don't reappear that aren't applicable here. e.g. mine. Thanks.

**Comment by cranes-bill** [comment]
Fine, but i think it will look better with square borders (just like the other stuff here).

**Comment by nowrep** [comment]
Alright, as @Martii said, please make this pull request again from clean branch (it's also good idea to use feature branches for all future pull requests).

Also, instead of configurable engine, let's just make it use default search engine.

**Comment by Diablopc** [comment]
@cranes-bill 
Like this?

> @nowrep pull request again from clean branch

Ok

> let's just make it use default search engine.

Hmm, idk how much it will be convenient because default search engine available from address bar.

**Comment by cranes-bill** [comment]
Yes square**d** :blush:, but that is only in my opinion.

**Pull request closed without merging**
