### PR TITLE
to fix the default zoom can be so?

### PR DESCRIPTION
**Pull request by wkg**

### CODE REVIEW

**Comment by nowrep** [comment]
Default zoom should be fixed in `master`, can you build it and try?

**Comment by wkg** [comment]
I'm sorry! realy fixed.... and favicons fixed! thank you! need only "JS Console" for me... will it?

**Comment by nowrep** [comment]
https://github.com/QupZilla/qupzilla/wiki/FAQ#16-there-is-no-web-inspector-in-qupzilla-20

**Comment by wkg** [comment]
thank you

**Comment by wkg** [comment]
sorry again! but zoom not fixed everything....
after restart browser - FIXED!
in second TAB(oppened from exists) - FIXED!
in the NEW TAB - NOT FIXED...

**Pull request closed without merging**
