### PR TITLE
 SpeedDial:

### PR DESCRIPTION
**Pull request by Diablopc**
- Reduced size of SpeedDial configuration overlay
- Added scrollbar to SDconfig for lowres screens 
- Fixed default background file
- Initial move "Add new dial" button to dials space
- Preserve side spase for config icon (now it not overlap dials) 
- Improved "settings" and "add" icons for use with light wallpaper 
- Added auto speeddial refresh while change configuration
- Updated vars names
- Replacement "broken-page" image to scalable
- Added qupzilla scalable icon
- Sliders restile
- Set inactive state for page size slider
- lock background in place
- lock in place "configure" and "add" buttons
- set proper default BG scaling
- Artwork: update svg metadata

### CODE REVIEW

**Comment by Diablopc** [comment]
btw
@nowrep due to this conversation https://github.com/Diablopc/qupzilla/commit/6163b0b1b680d656239c8b66949dec25de064a94#r26777190 seems need to review licensing for svg files.
What you think about this?

**Comment by nowrep** [comment]
https://community.kde.org/Policies/Licensing_Policy

It's your work, so it is up to you to decide which license to use. But I would prefer if you choose CC-BY-SA-4.0 as recommended by KDE for media files (images).
It should be enough to just put the notice in comment in all SVG files. Also if you can, please save the files optimized as @Martii said.

**Comment by Diablopc** [comment]
> so it is up to you to decide which license to use.

Haha, i had push it to public repo, this is mean that i have gifted it to all who needed this))
> I would prefer if you choose CC-BY-SA-4.0

Ok. Let it be CC-BY-SA-4.0
The main thing in this is to specify it correctly inside files


btw, how to correctly add new strings for translation?
because I changed a few of them here: https://github.com/QupZilla/qupzilla/pull/2543/commits/167982bb0ef2403ef6c03fd0a2f2500e955493d1#diff-fd87bcbf9f9270772361e42ac088636a
but not sure that this is enough ...

**Comment by nowrep** [comment]
> btw, how to correctly add new strings for translation?
because I changed a few of them here: 167982b#diff-fd87bcbf9f9270772361e42ac088636a
but not sure that this is enough ...

Yes, that's enough.

**Comment by Martii** [comment]
> It should be enough to just put the notice in comment in all SVG files

May run into CORS issues down the line. I've seen some backend and frontend development towards this goal of DRM. :\ Best to follow the specs for licensing instead of a comment. Once one is created then it won't be that difficult to copy/paste. :)

@Diablopc 
Ensure that the pretty-printing option is on with line breaks and indentations with indentation value of 1. I just redid my dev station and that's the default here... one never knows on older installst. This will be an easier read for commits down the line.

**Comment by Martii** [comment]
> https://community.kde.org/Policies/Licensing_Policy

Current bullet point 9 shows double licensing *(note the term change from dual)* which is more accurate for SVGs.... in SPDX terms this is an `AND` *(double... this and that required)* instead of `OR` *(dual... this or that)*.

Validating some xml tags I've run by so I can propose a possible template... give me a few.

**Comment by Martii** [comment]
> Haha, i had push it to public repo, this is mean that i have gifted it to all who needed this))

Not always... I'm not an attorney *(standard disclaimer but I have worked with several and the information was passed to me during my cognitive lifetime)*... You still maintain the Copyright but if you expect it to be merged in entirety you agree, at minimum, to the rights assigned in [LICENSE](https://github.com/QupZilla/qupzilla/blob/master/LICENSE). This is much like a TOS *(Terms of Service)* but a TOU *(Terms of Use)*. @nowrep and KDE have policies regarding submitting that applies for licensing e.g. leveraging who can distribute what. e.g with the proper CC you are granting others to use it as long as there is attribution *(probably the most important thing for FOSS)*. GPL requires source to be made always and forever, including all derivatives, a.k.a Copyleft. CC usually covers Content *(vague a.k.a. works in general but usually binary forms)* instead of Code *(very specific and usually in the clear)*.

So this is what was extrapolated using some modified W3 examples and interlaced/intertwined standards of metadata *(headers as Userscripts sometimes calls them)*:

``` svg
 <metadata id="license"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:cc="http://creativecommons.org/ns#">
  <rdf:RDF>
   <cc:Work rdf:about="https://github.com/QupZilla/qupzilla/blob/master/src/lib/data/html/sd_bg.svg">
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
    <dc:format>image/svg+xml</dc:format>
    <dc:source>https://raw.githubusercontent.com/QupZilla/qupzilla/master/src/lib/data/html/sd_bg.svg</dc:source>
    <dc:rights>https://github.com/QupZilla/qupzilla/blob/master/LICENSE</dc:rights>
    <dc:date>2018-01-12</dc:date>
    <dc:creator>Konstantin Savun</dc:creator>
    <cc:license rdf:resource="https://creativecommons.org/licenses/by-sa/4.0/legalcode"/>
    <cc:attributionName rdf:resource="Konstantin Savun"/>
    <cc:attributionURL rdf:resource="https://github.com/Diablopc"/>
    <dc:description>Optional - describe what this work is in human readable language preferably the projects default language.</dc:description>
   </cc:Work>
  </rdf:RDF>
</metadata>
```

This is probably the minimal generic template *(for that specific svg)* that someone would need to utilize a svg in distribution. 

It says who made it *(part of Copyright)*, where it was made *(useful for back referencing)*, when it was made *(the beginning the Copyright)*, what rights were initially granted to do this *(GPL-3.0)*, what rights are granted for *(optionally detached)* distribution *(CC-BY-SA-4.0)*, what kind of SVG it is *(animation or still image... there are others... useful for picking an appropriate editor and of course web servers knowing certain things to do before responding)*, and some other technical tags that describe Dublin Core metadata is used and CC metadata is used.

Finally if you want to optionally describe in human readable language the description of what it is/does that's the `<dc:description>` tag.

**Comment by nowrep** [comment]
With some adjustments I guess it can be used:

```xml
 <metadata id="license" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#">
  <rdf:RDF>
   <cc:Work rdf:about="sd_bg.svg">
    <dc:description>Speed Dial background</dc:description>
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
    <dc:format>image/svg+xml</dc:format>
    <dc:date>2018-01-10</dc:date>
    <dc:creator>Konstantin Savun</dc:creator>
    <cc:license rdf:resource="https://creativecommons.org/licenses/by-sa/4.0/legalcode"/>
    <cc:attributionName rdf:resource="Konstantin Savun"/>
    <cc:attributionURL rdf:resource="https://github.com/Diablopc"/>
   </cc:Work>
  </rdf:RDF>
</metadata>
```

Removed:
`<dc:source>` because it will be used also in Falkon and this url may change (either because github changes it or the file moves somewhere else)
`<dc:rights` because it points to LICENSE which is GPLv3, but this file is licenced with CC

And instead of `<cc:attributionURL` I would like to use e-mail.

**Comment by Diablopc** [comment]
@nowrep I had edit all svg in accordance with the recommendations and pushed them to  https://github.com/Diablopc/qupzilla-artwork. Pls review them so that I can push this to main repo.

@Martii thanks a lot for explanations.
I didn't understand anything about licensing =)))

**Comment by Martii** [comment]
@nowrep 

> `<dc:source>` because it will be used also in Falkon and this url may change (either because github changes it or the file moves somewhere else)

That's fine... was thinking about that before sleep last night. It's just a backreference that is handled by the original GPL licensing.

> `<dc:rights` because it points to LICENSE which is GPLv3, but this file is licensed with CC

But the rights initially granted come from a Code license. GPL requires this. You'll be in breach of the license without it. You can potentially lose your protections granted by GNU for failure to do this. Read the GPL licensing for Code. As I mentioned already SVG is mostly Code with the option of Content with a data URI in binary form. Plus you broke the ability to remove `<dc:source`.

I would **strongly suggest** that the rights key is kept.

**Comment by nowrep** [comment]
> But the rights initially granted come from a Code license. GPL requires this. You'll be in breach of the license without it. You can potentially lose your protections granted by GNU for failure to do this. Read the GPL licensing for Code. As I mentioned already SVG is mostly Code with the option of Content with a data URI in binary form. Plus you would break the ability to remove <dc:source.

No, even though SVG contains code, it should be treated as image file. These particular SVGs were all generated, not hand-written. And even if you treat it as code, how is it different? Just slap a license + your name and you are done? :D
I don't really understand what problem you mean here. Main license for QupZilla is GPLv3, but that doesn't mean that it can't use files with different licensing as long as it is compatible with GPLv3, which CC-BY-SA-4.0 is.

There are no initially granted rights if that particular file specify its own license, be it with license header in comment or like in the case here with SVGs.

And yeah, I don't really care that much about the licensing, it was already wasted much more time on this than it should have been. As far as I am concerned, having clear definition of what license is used for which files is enough for me. And in this case,  it is.

**Comment by Martii** [comment]
> No, even though SVG contains code, it should be treated as image file.

Absolutely Incorrect. Contact your legal counsel.

> it was already wasted much more time on this than it should have been

**That is your issue** not the contributors. If you don't want to honor the simple licensing here then you'll lose contributors. I've seen this a lot of times throughout the many decades in the industry. I'm doing my best to educate you from the information passed onto me with contract law with one of my fortes. If you don't honor GPL you may lose 100% of my contributions. I'm here because of GPL in this project. Please read and don't be stubborn by complaining that you've wasted too much time. It's your responsibility to ensure your project maintains availability on the KDE site now and not rejected.

**Comment by nowrep** [comment]
> If you don't want to honor the simple licensing here then you'll lose contributors.

But I do honor it. I just don't see the reason to overcomplicate it if not necessary.

I just don't understand why are those metadata tags so important. Does it mean that if you forget one of those 10 tags then your license is invalid? That's nonsense. And as you are mentioning KDE again, if you took a look how they handle SVG files then you would know that in most cases there is **no** mention of any license at all in the SVG source.

So for the last time, I don't care how the license is specified as long as it is there. Be it comment in SVG file, metadata tags or extra text file that mentions it.

**Comment by Diablopc** [comment]
About KDE repo: there really fully bullshit in svg metadata!
Part of files, as mentioned by David, have no MD at all, other files contains MD automatically generated by inkscape (with proprietary license), and i was not able find at least one with normal metadata. Idk what do they think, but it looks like they don't care about this anyway.

> That's nonsense

all jurisprudence - a solid nonsense
>  I don't care how the license is specified as long as it is there

Ok. at this time  i'll leave it in current state (as in qupzilla-artwork repo)

**Comment by Martii** [comment]
@Diablopc 

We'll just leave as a reactive issue then instead of a proactive one. e.g. will be handled on the redistribution side, and look the other way here as usual, and when the issue comes up down the line deal with it then. SVGs have been around a long time but their usage is only starting to come to mass usage with browser implementations *(take CORS for example which was already mentioned)*. Advice, information, and a proposal is just that... take it or leave.

I can't convey everything that I have learned with contract law because of time constraints and encountering the deficiencies for some who claim they waste time *(very poor wording from anyone)*. I appreciate your patience with the discussion and your eagerness to actually learn something new. That's a plus for you in observation. Maintainability is a balance between what's what right and what one does and/or doesn't want to do. I usually observe here to see what perceptions are viewed... back to that instead of pointing out referenced material as best I can within the time allotted.

> files contains MD automatically generated by inkscape

Everyone likes attribution for their work even the programs that assist. Important part of FOSS. I'm still 50/50 on removing the "created in" applications but if "Save as optimized" does it who am I to argue. ;) SVG is designed to describe artwork instead of just presenting it as a finished product. e.g. "show your work". Parsing the metadata is key for some distribution methods e.g. automation via programmatic means *(AI for the most advanced)* instead of human interaction with *(some)* guess work.

> (as in qupzilla-artwork repo)

Nice "side step" to avoid the issue... very diplomatic, clever, and probably the best to keep the hairs in place. 😸 

Anyhow... it's nice to see new feature artwork come to fruition. Look forward to it in a release :)

**Comment by andr222** [comment]
> Everyone likes attribution for their work even the programs that assist. Important part of FOSS. I'm still 50/50 on removing the "created in" applications but if "Save as optimized" does it who am I to argue. ;) SVG is designed to describe artwork instead of just presenting it as a finished product. e.g. "show your work". Parsing the metadata is key for some distribution methods e.g. automation via programmatic means (AI for the most advanced) instead of human interaction with (some) guess work.

The essence of image files is the appearance, not the algorithm of the code inside.
Image files can be under whatever license the creator wishes.
There is no requirement (under foss) that the license is referenced in every file, although putting reference to the license in every file is one way of avoiding ambiguity.

If an image or whatever other item with another license is distibuted as part of a collective work with a GPL license, the included item assumes the gpl license.
The included license must be GPL compatible.
In this case, CC is GPL compatible.
So the image file when distributed separately will be licensed CC, in the collective work will be GPL
Except for the initial licensing, nothing special need be done.

**Pull request merged**
