### PR TITLE
 Style Update [SpeedDial+SpeedDial:Icons]

### PR DESCRIPTION
**Pull request by Diablopc**

### CODE REVIEW

**Comment by nowrep** [comment]
I like it, but there is an issue with loading gif not being properly resized for very small dials (eg. set size to minimum = 100).

**Comment by Diablopc** [comment]
>  loading gif not being properly resized for very small dials

Hah, looks realy funny o_0

Yep, thats my bug. I haven't check this moments. 
Agree this is realy need some rework. I'll do it tomorrow...

**Comment by cranes-bill** [comment]
@nowrep Now is the moment to consider merging `start` page with `speeddial`?

**Comment by Diablopc** [comment]
@cranes-bill it's planned, but not all at once =)

**Comment by Diablopc** [comment]
> loading gif not being properly resized 

Fixed by 5d76be6

> It's fine those buttons being big for very small dials, but they should also resize when on very big dials (eg. maximum size = 500).

Fixed by a60dd0c

- Min button size set to 16. 
- Max button size not limited and depends of dial size


Also:
- Added default background
- Fixed incorrect tiles enumeration [[7bc8123]]
- Fully switched to scalable graphics

@nowrep what U think about?

**Comment by nowrep** [comment]
Perfect

**Comment by Diablopc** [comment]
@nowrep 
Pls, update this file in yours repo.
https://github.com/Diablopc/qupzilla/blob/master/src/lib/data/html/sd_bg.svg
It was broken =(

**Comment by cranes-bill** [comment]
Why the modal dialog overfills the window!?
capture du 2018-01-11 08 35 43
And if i enable the bookmarks bar, it's getting badly:
capture du 2018-01-11 08 37 40

**Comment by Diablopc** [comment]
@cranes-bill already working on this!

**Comment by nowrep** [comment]
This is a long-standing issue, maybe we can move background selection to second column?

**Comment by Diablopc** [comment]
@nowrep I've already added a scrollbar for cases where content can't fit to screen.
Commit will be in one hour

**Comment by nowrep** [comment]
I'd rather have it in two columns instead of adding scrollbars.

**Comment by Diablopc** [comment]
@nowrep But then we must add a horisontal scroll due to portrait screens...

I have some idea how to decrease vertical size without layout changes...
Wait aproximately a hour, i'll try to do that

**Comment by Diablopc** [comment]
@nowrep 
Here is it


Scrollbar appears only if active area lower than 550px.
This is enough to not show it on low resolution screens inclusive 768px height

**Comment by nowrep** [comment]
Ok, that looks fine. Can you ale please hide size of pages slider when "change size of pages" is unchecked? It's kind of confusing as the disabled state is not easy to distinguish.

**Comment by Diablopc** [comment]
> Can you also please hide size of pages slider when "change size of pages" is unchecked?

Sure, it planned.
In the nearest future planned to move "Add" button to dial space and restile sliders to common style, also with this i'll hide unused messages =)

**Comment by nowrep** [comment]
I need your full name, otherwise I can't push this to Falkon repo. And that applies for all following commits too, please commit with full name.

**Comment by Diablopc** [comment]
Ou, that's not a problem =)
I hope it enough just to add this to my profile?

**Comment by nowrep** [comment]
Alright, thanks.

>  I hope it enough just to add this to my profile?

Only if you commit through github webpage. You need to set it in your git config.

**Comment by Diablopc** [comment]
> You need to set it in your git config.

Ok. It  will be done before next commit.

**Comment by cranes-bill** [comment]
Noticed onother one unintended behaviour:
I have `Don't close window upon closing last tab` option  set. So when i close the last one tab, the result is an empty Speed dial.
capture du 2018-01-12 22 12 07

**Comment by Diablopc** [comment]
> @cranes-bill I have Don't close window

it looks weird .... I'm use this option to, but never noticed such behavior...
btw try to pick it up from my repo, there was a lot of changes that not applied in main repo

**Comment by nowrep** [comment]
@cranes-bill That has nothing to do with this, you should open separate issue for this.

**Comment by cranes-bill** [comment]
> ..., you should open separate issue for this.

That was my initial plan, but due to i'm avoiding of „non sense issues“, decided posting here.
But now, since you tel, i will open a new issue.

**Pull request merged**
