### PR TITLE
Opt some images

### PR DESCRIPTION
**Pull request by Martii**
Footprint improvements

---

PR READY

### CODE REVIEW

**Comment by Martii** [comment]
Here's the stats for this PR btw... was waiting for a merge to do this:

``` sh-session
 bin/themes/breathe/images/goto.png                 | Bin 641 -> 608 bytes
 bin/themes/breathe/images/navigation-dropdown.png  | Bin 415 -> 373 bytes
 bin/themes/breathe/images/semi-transp.png          | Bin 150 -> 146 bytes
 bin/themes/breathe/images/star.png                 | Bin 657 -> 654 bytes
 bin/themes/breathe/images/stop.png                 | Bin 1078 -> 1076 bytes
 bin/themes/breathe/images/websearch-bg-a.png       | Bin 445 -> 436 bytes
 bin/themes/breathe/images/websearch-bg-h.png       | Bin 346 -> 345 bytes
 bin/themes/breathe/images/websearch-bg.png         | Bin 335 -> 334 bytes
 bin/themes/chrome/images/gotoaddress.png           | Bin 612 -> 610 bytes
 bin/themes/chrome/images/key.png                   | Bin 713 -> 682 bytes
 bin/themes/chrome/images/navigation-addtab.png     | Bin 2963 -> 2960 bytes
 bin/themes/chrome/images/navigation-dropdown.png   | Bin 526 -> 493 bytes
 bin/themes/chrome/images/navigation-reload.png     | Bin 4110 -> 4101 bytes
 bin/themes/chrome/images/navigation-stop.png       | Bin 3797 -> 3791 bytes
 bin/themes/chrome/images/semi-transp.png           | Bin 150 -> 146 bytes
 bin/themes/chrome/images/tab-left-arrow.png        | Bin 192 -> 177 bytes
 bin/themes/chrome/images/tab-right-arrow.png       | Bin 188 -> 175 bytes
 bin/themes/chrome/images/tabs-bg.png               | Bin 320 -> 306 bytes
 bin/themes/chrome/images/toolbar-bg.png            | Bin 247 -> 246 bytes
 bin/themes/chrome/images/toolbutton-h.png          | Bin 1322 -> 1319 bytes
 bin/themes/chrome/images/toolbutton.png            | Bin 1000 -> 972 bytes
 bin/themes/default/images/arrow-down.gif           | Bin 54 -> 54 bytes
 bin/themes/default/images/background.png           | Bin 16826 -> 16804 bytes
 bin/themes/default/images/gotoaddress.png          | Bin 612 -> 610 bytes
 bin/themes/default/images/key.png                  | Bin 713 -> 682 bytes
 bin/themes/default/images/lineedit-bg.png          | Bin 529 -> 521 bytes
 bin/themes/default/images/navigation-home.png      | Bin 920 -> 815 bytes
 bin/themes/default/images/semi-transp.png          | Bin 150 -> 146 bytes
 bin/themes/default/images/siteicon-bg.png          | Bin 655 -> 653 bytes
 bin/themes/default/images/tab-left-arrow.png       | Bin 192 -> 177 bytes
 bin/themes/default/images/tab-right-arrow.png      | Bin 188 -> 175 bytes
 bin/themes/default/images/websearchbar-bg.png      | Bin 654 -> 621 bytes
 bin/themes/linux/images/goto.png                   | Bin 641 -> 608 bytes
 bin/themes/linux/images/key.png                    | Bin 713 -> 682 bytes
 bin/themes/linux/images/menu.png                   | Bin 284 -> 235 bytes
 bin/themes/linux/images/navigation-dropdown.png    | Bin 189 -> 167 bytes
 bin/themes/linux/images/semi-transp.png            | Bin 150 -> 146 bytes
 bin/themes/linux/images/star.png                   | Bin 650 -> 451 bytes
 bin/themes/linux/images/tab-left-arrow.png         | Bin 192 -> 177 bytes
 bin/themes/linux/images/tab-right-arrow.png        | Bin 188 -> 175 bytes
 bin/themes/mac/images/gotoaddress.png              | Bin 612 -> 610 bytes
 bin/themes/mac/images/key.png                      | Bin 713 -> 682 bytes
 bin/themes/mac/images/lineedit-bg.png              | Bin 270 -> 258 bytes
 bin/themes/mac/images/navigation-dropdown.png      | Bin 221 -> 184 bytes
 bin/themes/mac/images/searchbar-provider-bg.png    | Bin 1343 -> 1300 bytes
 bin/themes/mac/images/semi-transp.png              | Bin 150 -> 146 bytes
 bin/themes/mac/images/siteicon-bg.png              | Bin 1314 -> 1292 bytes
 bin/themes/mac/images/siteicon-secure-bg.png       | Bin 991 -> 951 bytes
 bin/themes/mac/images/tab-left-arrow.png           | Bin 192 -> 177 bytes
 bin/themes/mac/images/tab-right-arrow.png          | Bin 188 -> 175 bytes
 bin/themes/mac/images/tabs-bg.png                  | Bin 153 -> 140 bytes
 bin/themes/mac/images/tabs-list-button.png         | Bin 308 -> 258 bytes
 bin/themes/mac/images/tabs-list-button_rtl.png     | Bin 310 -> 259 bytes
 bin/themes/mac/images/toolbar-bg.png               | Bin 169 -> 158 bytes
 bin/themes/mac/images/user-trash-full.png          | Bin 1108 -> 1097 bytes
 bin/themes/windows/images/gotoaddress.png          | Bin 612 -> 610 bytes
 bin/themes/windows/images/key.png                  | Bin 713 -> 682 bytes
 bin/themes/windows/images/navigation-dropdown.png  | Bin 737 -> 668 bytes
 bin/themes/windows/images/navigation-forward.png   | Bin 4956 -> 4940 bytes
 .../windows/images/searchbar-provider-bg.png       | Bin 230 -> 207 bytes
 bin/themes/windows/images/semi-transp.png          | Bin 150 -> 146 bytes
 bin/themes/windows/images/siteicon-bg.png          | Bin 185 -> 170 bytes
 bin/themes/windows/images/star-a.png               | Bin 653 -> 579 bytes
 bin/themes/windows/images/tab-active-bg.png        | Bin 194 -> 193 bytes
 .../windows/images/tab-deactive-hover-bg.png       | Bin 130 -> 127 bytes
 bin/themes/windows/images/tab-left-arrow.png       | Bin 192 -> 177 bytes
 bin/themes/windows/images/tab-right-arrow.png      | Bin 188 -> 175 bytes
 .../windows/images/tabbar-addtab-outside.png       | Bin 223 -> 172 bytes
 bin/themes/windows/images/toolbar-bg.png           | Bin 232 -> 193 bytes
 bin/themes/windows/images/user-trash-full.png      | Bin 1108 -> 1097 bytes
 linux/hicolor/16x16/apps/qupzilla.png              | Bin 746 -> 709 bytes
 linux/hicolor/256x256/apps/qupzilla.png            | Bin 23821 -> 23819 bytes
 linux/hicolor/32x32/apps/qupzilla.png              | Bin 1730 -> 1715 bytes
 linux/hicolor/48x48/apps/qupzilla.png              | Bin 2880 -> 2848 bytes
 linux/hicolor/64x64/apps/qupzilla.png              | Bin 4059 -> 4036 bytes
 linux/pixmaps/qupzilla.png                         | Bin 2880 -> 2848 bytes
 mac/images/qupzilla-dmg-background.png             | Bin 41878 -> 41176 bytes
 mac/images/qupzilla-dmg-icon.png                   | Bin 49209 -> 48958 bytes
 other/linguist-set-language.png                    | Bin 28923 -> 24577 bytes
 other/linguist-translating.png                     | Bin 123198 -> 106272 bytes
 src/lib/data/html/broken-page.png                  | Bin 2809 -> 2795 bytes
 src/lib/data/html/configure.png                    | Bin 1374 -> 1172 bytes
 src/lib/data/html/loading.gif                      | Bin 1924 -> 1775 bytes
 src/lib/data/html/plus.png                         | Bin 774 -> 717 bytes
 src/lib/data/icons/browsers/chrome.png             | Bin 3809 -> 2470 bytes
 src/lib/data/icons/browsers/firefox.png            | Bin 5439 -> 4415 bytes
 src/lib/data/icons/browsers/html.png               | Bin 3824 -> 3822 bytes
 src/lib/data/icons/browsers/internet-explorer.png  | Bin 1060 -> 1372 bytes
 src/lib/data/icons/browsers/opera.png              | Bin 2920 -> 1408 bytes
 src/lib/data/icons/exeicons/page.ico               | Bin 15086 -> 15086 bytes
 src/lib/data/icons/exeicons/page16.png             | Bin 665 -> 506 bytes
 src/lib/data/icons/exeicons/page32.png             | Bin 1422 -> 1146 bytes
 src/lib/data/icons/exeicons/page48.png             | Bin 2142 -> 1560 bytes
 src/lib/data/icons/exeicons/qupzilla-window.png    | Bin 23821 -> 23819 bytes
 src/lib/data/icons/exeicons/qupzilla.ico           | Bin 370070 -> 125412 bytes
 src/lib/data/icons/locationbar/visit2.png          | Bin 1419 -> 1383 bytes
 src/lib/data/icons/menu/history.png                | Bin 862 -> 786 bytes
 src/lib/data/icons/menu/history_entry.png          | Bin 878 -> 803 bytes
 src/lib/data/icons/menu/qt.png                     | Bin 744 -> 719 bytes
 src/lib/data/icons/menu/search-icon.png            | Bin 935 -> 863 bytes
 src/lib/data/icons/menu/tab.png                    | Bin 441 -> 423 bytes
 src/lib/data/icons/other/about.png                 | Bin 9873 -> 9710 bytes
 src/lib/data/icons/other/adblock-disabled.png      | Bin 466 -> 454 bytes
 src/lib/data/icons/other/adblock.png               | Bin 763 -> 684 bytes
 src/lib/data/icons/other/empty-page.png            | Bin 530 -> 515 bytes
 src/lib/data/icons/other/loading.png               | Bin 4159 -> 2873 bytes
 src/lib/data/icons/other/loading@2x.png            | Bin 29802 -> 6353 bytes
 src/lib/data/icons/other/login.png                 | Bin 1205 -> 1174 bytes
 src/lib/data/icons/other/notification.png          | Bin 1150 -> 1127 bytes
 src/lib/data/icons/preferences/text-x-sql.png      | Bin 1768 -> 1669 bytes
 src/lib/data/icons/qupzilla.png                    | Bin 657 -> 466 bytes
 src/lib/data/icons/sites/aol.png                   | Bin 358 -> 312 bytes
 src/lib/data/icons/sites/duck.png                  | Bin 796 -> 734 bytes
 src/lib/data/icons/sites/startpage.png             | Bin 756 -> 731 bytes
 src/lib/data/icons/sites/w3.png                    | Bin 593 -> 491 bytes
 .../data/oxygen-fallback/16x16/bookmark-new.png    | Bin 707 -> 700 bytes
 src/lib/data/oxygen-fallback/16x16/configure.png   | Bin 717 -> 677 bytes
 .../data/oxygen-fallback/16x16/dialog-close.png    | Bin 813 -> 791 bytes
 .../oxygen-fallback/16x16/go-jump-locationbar.png  | Bin 641 -> 608 bytes
 src/lib/data/oxygen-fallback/16x16/list-remove.png | Bin 332 -> 327 bytes
 .../data/oxygen-fallback/16x16/process-stop.png    | Bin 722 -> 698 bytes
 src/lib/data/oxygen-fallback/16x16/window-new.png  | Bin 377 -> 354 bytes
 src/lib/data/oxygen-fallback/22x22/configure.png   | Bin 1101 -> 1044 bytes
 src/lib/data/oxygen-fallback/22x22/go-down.png     | Bin 892 -> 883 bytes
 .../oxygen-fallback/22x22/go-jump-locationbar.png  | Bin 957 -> 934 bytes
 .../data/oxygen-fallback/22x22/process-stop.png    | Bin 1078 -> 1076 bytes
 src/lib/data/oxygen-fallback/22x22/tab-new.png     | Bin 791 -> 759 bytes
 .../data/oxygen-fallback/22x22/user-trash-full.png | Bin 1108 -> 1097 bytes
 src/lib/data/oxygen-fallback/22x22/window-new.png  | Bin 680 -> 656 bytes
 src/lib/data/qupzilla.png                          | Bin 2880 -> 2848 bytes
 src/plugins/AutoScroll/data/scroll_all.png         | Bin 1811 -> 1538 bytes
 src/plugins/AutoScroll/data/scroll_horizontal.png  | Bin 1734 -> 1492 bytes
 src/plugins/AutoScroll/data/scroll_vertical.png    | Bin 1714 -> 1485 bytes
 .../data/flash-cookie-manager.png                  | Bin 30437 -> 30383 bytes
 src/plugins/GnomeKeyringPasswords/data/icon.png    | Bin 2288 -> 2091 bytes
 src/plugins/GreaseMonkey/data/icon16.png           | Bin 994 -> 988 bytes
 src/plugins/GreaseMonkey/data/icon18.png           | Bin 1159 -> 1153 bytes
 src/plugins/GreaseMonkey/data/script.png           | Bin 1064 -> 1043 bytes
 src/plugins/ImageFinder/data/icon.png              | Bin 1240 -> 869 bytes
 src/plugins/ImageFinder/data/tineye.png            | Bin 1325 -> 1323 bytes
 src/plugins/ImageFinder/data/yandex.png            | Bin 861 -> 846 bytes
 src/plugins/KWalletPasswords/data/icon.png         | Bin 1826 -> 1804 bytes
 src/plugins/StatusBarIcons/data/images.png         | Bin 659 -> 658 bytes
 src/plugins/StatusBarIcons/data/javascript.png     | Bin 680 -> 675 bytes
 .../StatusBarIcons/data/network-unknown.png        | Bin 941 -> 845 bytes
 src/plugins/TabManager/data/side-by-side.png       | Bin 939 -> 898 bytes
 src/plugins/TabManager/data/tab-bookmark.png       | Bin 807 -> 689 bytes
 src/plugins/TabManager/data/tab-detach.png         | Bin 784 -> 709 bytes
 src/plugins/TabManager/data/tab-pinned.png         | Bin 2428 -> 2416 bytes
 src/plugins/TabManager/data/tabmanager.png         | Bin 7417 -> 7018 bytes
 windows/install.ico                                | Bin 9662 -> 9662 bytes
 windows/uninstall.ico                              | Bin 9662 -> 9662 bytes
```

**Comment by GreenLunar** [comment]
Which command did you use?

Was it `optipng -o7 $(find -iname '*.png')`?

See fee1a78ef0975bd0638741e9fa08d8e534faeed4

**Comment by nowrep** [comment]
Yeah, that's a good comment. Would be great if you add a script that optimizes all images, or at least write the command used somewhere.

**Comment by Martii** [comment]
A lot of hard work and a lot of `pngcrush`es as I alluded to in the commit message... the rest were manual resaves using various image editors trying the best one. There really isn't one program that does it all.

**Comment by nowrep** [comment]
Ok no problem.

**Comment by Martii** [comment]
That's because I got the commit in before you merged.

**Comment by GreenLunar** [comment]
Wow!

**Comment by Martii** [comment]
Yah took me 5 hours.

**Pull request merged**
