### PR TITLE
Make AppData translatable

### LINKED ISSUE #1704: [i18n] Make AppData file translatable
~~Consider writing and installing an AppData file with the application description and some screenshots, else QupZilla would look bad in the GNOME and KDE Software Centers.~~

~~See these links for details.~~
~~http://people.freedesktop.org/~hughsient/appdata/~~
~~https://github.com/hughsie/appdata-tools~~

### PR DESCRIPTION
**Pull request by GreenLunar**
Partially fixes #1704

### CODE REVIEW

**Comment by nowrep** [comment]
Why just partially? It makes it translatable, what more we need?

**Comment by GreenLunar** [comment]
I do not know.  @hughsie may you please guide us?

**Comment by GreenLunar** [comment]
@gottcode, how do you manage AppData files of your projects?

**Comment by gottcode** [comment]
@GreenLunar I use a hackish solution. I wrote a Bash script to call ```intltool-extract``` to fetch the strings of the desktop and appdata files, then run ```xgettext``` on those files to create a .pot file, and then run ```msgmerge``` to update the .po files with new strings, and finally run ```intltool-merge``` to copy the translations back from the .po files into the desktop and appdata files. You can see the script here: https://github.com/gottcode/focuswriter/blob/master/resources/unix/po/update-po.sh

**Comment by GreenLunar** [comment]
Thank you, Graeme.  I think such solution is acceptable, as [qupzilla.desktop](https://github.com/QupZilla/qupzilla/blob/v1.8/linux/applications/qupzilla.desktop) is also static.

**Comment by GreenLunar** [comment]
Which means, if your solution will be accepted, that this commit is of no use.

**Comment by gottcode** [comment]
I'm glad I could be of assistance.

**Pull request closed without merging**
