### PR TITLE
Add Slovenian translation for the application

### PR DESCRIPTION
**Pull request by matijaskala**

### CODE REVIEW

**Comment by nowrep** [comment]
Please add it at https://www.transifex.com/projects/p/qupzilla

**Comment by matijaskala** [comment]
Can you enable Slovenian language? I cannot join until then.

**Comment by nowrep** [comment]
You can request adding new language, so please do it and I'll accept it. Thanks

**Comment by matijaskala** [comment]
I already did. And I cannot request it twice.

**Comment by matijaskala** [comment]
I requested to join. Can you add me to the team?

**Pull request closed without merging**
